/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hutech.appthitracnghiemonline.client.da;

import com.hutech.appthitracnghiemonline.client.Client;
import static com.hutech.appthitracnghiemonline.client.Client.client;
import static com.hutech.appthitracnghiemonline.client.Client.port;
import static com.hutech.appthitracnghiemonline.client.da.frmExercise1.din;
import static com.hutech.appthitracnghiemonline.client.da.frmExercise1.dout;
import static com.hutech.appthitracnghiemonline.client.da.frmExercise1.test;
import com.hutech.appthitracnghiemonline.server.Server;
import com.hutech.appthitracnghiemonline.server.model.BaiThi;
import com.hutech.appthitracnghiemonline.server.model.CauLam;
import com.hutech.appthitracnghiemonline.server.model.DeThi;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author ADMIN
 */
public class frmExercise1 extends javax.swing.JFrame {

    public static int i = 0;
    public static int guiKetQua = 1;
    int counter = 30;
    Boolean isIt = false;
    public static Client c = new Client();
    public static Socket client = null;
    public static int port = 8888;
    public static Scanner sc = new Scanner(System.in);
    public static DeThi test = null;
    public static BaiThi bt = null;
    public static ObjectOutputStream dout = null;
    public static ObjectInputStream din = null;
    public static int ctl = 0;
    public static frmExercise1 frm = null;
    public static ArrayList<CauLam> arrList = new ArrayList<CauLam>(10);
    public static int dapan = 0;
    public static int STOP = 1;
    public Timer timer = null;
    public static String mssv;

    /**
     *
     * Creates new form frmExercise
     */
//    public frmExercise(Socket sk) {
//        initComponents();
//        this.client = sk;
//        label_stt.setText("CÂU 1");
////        label_cauhoi.setText(test.dsCauHoi.get(0).noiDung);
////        rdo_caua.setText(test.dsCauHoi.get(0).cauA);
////        rdo_caub.setText(test.dsCauHoi.get(0).cauB);
////        rdo_cauc.setText(test.dsCauHoi.get(0).cauC);
////        rdo_caud.setText(test.dsCauHoi.get(0).cauD);
//        
//    }
    public frmExercise1(Socket client, DeThi test) {
        frmExercise1.test = test;
        frmExercise1.client = client;
        this.setLocationRelativeTo(null);
        initComponents();
        hienCauHoi(test);
        tinhGio();
    }

    public frmExercise1(ObjectOutputStream gui, ObjectInputStream nhan, DeThi test, String mssv) {

        dout = gui;
        din = nhan;
        this.mssv = mssv;
        frmExercise1.test = test;
        this.setLocationRelativeTo(null);
        initComponents();
        hienCauHoi(test);
        tinhGio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        timeLeft = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        label_stt = new javax.swing.JLabel();
        caud = new javax.swing.JRadioButton();
        cauc = new javax.swing.JRadioButton();
        caub = new javax.swing.JRadioButton();
        caua = new javax.swing.JRadioButton();
        label_cauhoi = new javax.swing.JLabel();
        btn_tiep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BÀI TẬP TRẮC NGHIỆM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_alarm_clock_50px.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        timeLeft.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        timeLeft.setForeground(new java.awt.Color(255, 0, 0));
        timeLeft.setText("30");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_next_page_50px_1.png"))); // NOI18N
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText(" NỘP BÀI");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_stt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_stt.setText("CÂU 1");

        cauc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caucActionPerformed(evt);
            }
        });

        label_cauhoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_cauhoi.setText("Tại sao chúng ta nên học mạng máy tính");

        btn_tiep.setText("TIẾP");
        btn_tiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tiepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_tiep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(timeLeft)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(label_stt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(533, 533, 533)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(caud)
                            .addComponent(caub)
                            .addComponent(cauc)
                            .addComponent(caua)
                            .addComponent(label_cauhoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(44, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(322, 322, 322)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(430, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cauhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_stt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(caua)
                .addGap(18, 18, 18)
                .addComponent(caub)
                .addGap(18, 18, 18)
                .addComponent(cauc)
                .addGap(18, 18, 18)
                .addComponent(caud)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tiep)
                        .addGap(51, 51, 51))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(394, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel4AncestorAdded

    }//GEN-LAST:event_jLabel4AncestorAdded

    private void caucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caucActionPerformed

    private void btn_tiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tiepActionPerformed
        ++i;
        if (i == 10) {
            timer.cancel();
            try {
                tinh_diem();
            } catch (IOException ex) {
                Logger.getLogger(frmExercise1.class.getName()).log(Level.SEVERE, null, ex);
            }
            new frmResult(bt).setVisible(true);
            this.setVisible(false);
            this.dispose();
            STOP = 0;

        } else {
            timer.cancel();
            hienCauHoi(test);
            tinhGio();
        }
    }//GEN-LAST:event_btn_tiepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, ClassNotFoundException {

        System.out.println("Nội dung bài thi: 10 câu trắc nghiệm - mỗi câu 30 giây làm bài");
//        test = (DeThi)din.readObject();
//        System.out.println(test.dsCauHoi.toString());
//        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                frm = new frmExercise1(client, test);
                frm.setVisible(true);
            }
        });
    }
//hàm tính giờ

    public void tinhGio() {
        try {

            timer = new Timer(); //new timer
            if (i == 10) {
                timer.cancel();
            } else {
                counter = 30; //setting the counter to 30 sec
                TimerTask task;
                task = new TimerTask() {
                    public void run() {
                        timeLeft.setText(Integer.toString(counter));
                        counter--;
                        System.out.println(counter);
                        if (counter <= 0 && i >= test.dsCauHoi.size() - 1) {
                            JOptionPane.showMessageDialog(null,
                                    "Chúc mừng bạn đã HOÀN THÀNH bài kiểm tra. Hệ thống đang xử lý kết quả kiểm tra!", "HOÀN THÀNH", JOptionPane.INFORMATION_MESSAGE);
                           

                            STOP = 0;

                            timer.cancel();
                            try {
                                System.out.println("Bat dau gui bai thi len server");
                                tinh_diem();
                                new frmResult(bt).setVisible(true);

                            } catch (IOException ex) {
                                Logger.getLogger(frmExercise1.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            timer.cancel();

                            System.exit(0);

                        } else if (counter == 5 && dapan == 0) {
//                            JOptionPane.showMessageDialog(null,
//                                    "Chú ý gần hết thời gian. Vui lòng hoàn thành đáp án!", "Chú ý", JOptionPane.ERROR_MESSAGE);
                        } else if (counter == -1 && i != 10) {
                            timer.cancel();
                            ++i;
                            hienCauHoi(test);
                            tinhGio();

                        } else if (isIt) {
                            timer.cancel();
                            isIt = false;
                        }

                    }
                };
                timer.scheduleAtFixedRate(task, 1000, 1000); // =  timer.scheduleAtFixedRate(task, delay, period);
            }
        } catch (Exception e) {
        }
    }

    //hiện câu hoi
    public static void hienCauHoi(DeThi test) {
        try {
       
//                caua.setSelected(false);
//                caub.setSelected(false);
//                cauc.setSelected(false);
//                caud.setSelected(false);
//                
            label_stt.setText("CÂU " + (i + 1));
            label_cauhoi.setText(test.dsCauHoi.get(i).noiDung);
            caua.setText(test.dsCauHoi.get(i).cauA);
            caub.setText(test.dsCauHoi.get(i).cauB);
            cauc.setText(test.dsCauHoi.get(i).cauC);
            caud.setText(test.dsCauHoi.get(i).cauD);
            //lưu các câu làm vào trong list CauLam
            dapan = 0;
            if (caua.isSelected()) {
                dapan = 1;
            } else if (caub.isSelected()) {
                dapan = 2;
            } else if (cauc.isSelected()) {
                dapan = 3;
            } else if (caud.isSelected()) {
                dapan = 4;
            } else {
                dapan = 0; //rang buoc dap an
            }
            CauLam cl = new CauLam(test.dsCauHoi.get(i), dapan);
            arrList.add(cl);
        } catch (Exception e) {
        }
    }

    //gửi kết quả về server
    public static void tinh_diem() throws IOException {

        //lưu bài thi để gưi về server
//        System.out.println("123");
//        System.out.println( arrList.get(1).cauChon + " CAU TRA LOI");
        //lưu danh sách các câu làm
        bt = new BaiThi(mssv, test.maDe);
        bt.dsCauLam = arrList;
        bt.tinhDiem();
        System.out.println("Bat dau gui bai thi len server");
        dout.writeInt(Server.GUIDETHI);
        dout.flush();
        dout.writeObject(bt);
        dout.flush();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tiep;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    public static javax.swing.JRadioButton caua;
    public static javax.swing.JRadioButton caub;
    public static javax.swing.JRadioButton cauc;
    public static javax.swing.JRadioButton caud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JLabel label_cauhoi;
    public static javax.swing.JLabel label_stt;
    private javax.swing.JLabel timeLeft;
    // End of variables declaration//GEN-END:variables
}
